//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace QuestionsYourFriendsDataAccessPoco
{
    public partial class Transac
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual long fid
        {
            get;
            set;
        }
    
        public virtual int amount
        {
            get;
            set;
        }
    
        public virtual string status
        {
            get;
            set;
        }
    
        public virtual int userId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (User != null && User.id != value)
                    {
                        User = null;
                    }
                    _userId = value;
                }
            }
        }
        private int _userId;

        #endregion
        #region Navigation Properties
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion
        #region Association Fixup
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.Transacs.Contains(this))
            {
                previousValue.Transacs.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.Transacs.Contains(this))
                {
                    User.Transacs.Add(this);
                }
                if (userId != User.id)
                {
                    userId = User.id;
                }
            }
        }

        #endregion
    }
}
