//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.225
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("QuestionYourFriendsModel", "FK_Question_Owner", "User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QuestionYourFriendsDataAccess.User), "Question", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QuestionYourFriendsDataAccess.Question))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("QuestionYourFriendsModel", "FK_Question_Receiver", "User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QuestionYourFriendsDataAccess.User), "Question", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QuestionYourFriendsDataAccess.Question))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("QuestionYourFriendsModel", "FK_Transac_Question", "Question", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(QuestionYourFriendsDataAccess.Question), "Transac", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QuestionYourFriendsDataAccess.Transac))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("QuestionYourFriendsModel", "FK_Transac_User", "User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QuestionYourFriendsDataAccess.User), "Transac", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QuestionYourFriendsDataAccess.Transac))]

// Nom du fichier d'origine :
// Date de génération : 12/06/2011 21:09:13
namespace QuestionYourFriendsDataAccess
{
    
    /// <summary>
    /// Il n'existe aucun commentaire pour QuestionYourFriendsEntities dans le schéma.
    /// </summary>
    public partial class QuestionYourFriendsEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initialise un nouvel objet QuestionYourFriendsEntities à l'aide de la chaîne de connexion trouvée dans la section « QuestionYourFriendsEntities » du fichier de configuration d'application.
        /// </summary>
        public QuestionYourFriendsEntities() : 
                base("name=QuestionYourFriendsEntities", "QuestionYourFriendsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialise un nouvel objet QuestionYourFriendsEntities.
        /// </summary>
        public QuestionYourFriendsEntities(string connectionString) : 
                base(connectionString, "QuestionYourFriendsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialise un nouvel objet QuestionYourFriendsEntities.
        /// </summary>
        public QuestionYourFriendsEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "QuestionYourFriendsEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Il n'existe aucun commentaire pour Questions dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Question> Questions
        {
            get
            {
                if ((this._Questions == null))
                {
                    this._Questions = base.CreateQuery<Question>("[Questions]");
                }
                return this._Questions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Question> _Questions;
        /// <summary>
        /// Il n'existe aucun commentaire pour Transacs dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Transac> Transacs
        {
            get
            {
                if ((this._Transacs == null))
                {
                    this._Transacs = base.CreateQuery<Transac>("[Transacs]");
                }
                return this._Transacs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Transac> _Transacs;
        /// <summary>
        /// Il n'existe aucun commentaire pour Users dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<User> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<User>("[Users]");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<User> _Users;
        /// <summary>
        /// Il n'existe aucun commentaire pour Questions dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToQuestions(Question question)
        {
            base.AddObject("Questions", question);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Transacs dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToTransacs(Transac transac)
        {
            base.AddObject("Transacs", transac);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Users dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour QuestionYourFriendsModel.Question dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QuestionYourFriendsModel", Name="Question")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Question : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet Question.
        /// </summary>
        /// <param name="id">Valeur initiale de id.</param>
        /// <param name="text">Valeur initiale de text.</param>
        /// <param name="anom_price">Valeur initiale de anom_price.</param>
        /// <param name="private_price">Valeur initiale de private_price.</param>
        /// <param name="undesirable">Valeur initiale de undesirable.</param>
        /// <param name="date_pub">Valeur initiale de date_pub.</param>
        /// <param name="deleted">Valeur initiale de deleted.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Question CreateQuestion(int id, string text, int anom_price, int private_price, bool undesirable, global::System.DateTime date_pub, bool deleted)
        {
            Question question = new Question();
            question.id = id;
            question.text = text;
            question.anom_price = anom_price;
            question.private_price = private_price;
            question.undesirable = undesirable;
            question.date_pub = date_pub;
            question.deleted = deleted;
            return question;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété text dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string text
        {
            get
            {
                return this._text;
            }
            set
            {
                this.OntextChanging(value);
                this.ReportPropertyChanging("text");
                this._text = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("text");
                this.OntextChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _text;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntextChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntextChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété answer dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string answer
        {
            get
            {
                return this._answer;
            }
            set
            {
                this.OnanswerChanging(value);
                this.ReportPropertyChanging("answer");
                this._answer = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("answer");
                this.OnanswerChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _answer;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnanswerChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnanswerChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété anom_price dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int anom_price
        {
            get
            {
                return this._anom_price;
            }
            set
            {
                this.Onanom_priceChanging(value);
                this.ReportPropertyChanging("anom_price");
                this._anom_price = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("anom_price");
                this.Onanom_priceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _anom_price;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onanom_priceChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onanom_priceChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété private_price dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int private_price
        {
            get
            {
                return this._private_price;
            }
            set
            {
                this.Onprivate_priceChanging(value);
                this.ReportPropertyChanging("private_price");
                this._private_price = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("private_price");
                this.Onprivate_priceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _private_price;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onprivate_priceChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onprivate_priceChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété undesirable dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool undesirable
        {
            get
            {
                return this._undesirable;
            }
            set
            {
                this.OnundesirableChanging(value);
                this.ReportPropertyChanging("undesirable");
                this._undesirable = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("undesirable");
                this.OnundesirableChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _undesirable;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnundesirableChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnundesirableChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété date_pub dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime date_pub
        {
            get
            {
                return this._date_pub;
            }
            set
            {
                this.Ondate_pubChanging(value);
                this.ReportPropertyChanging("date_pub");
                this._date_pub = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("date_pub");
                this.Ondate_pubChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _date_pub;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondate_pubChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondate_pubChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété date_answer dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> date_answer
        {
            get
            {
                return this._date_answer;
            }
            set
            {
                this.Ondate_answerChanging(value);
                this.ReportPropertyChanging("date_answer");
                this._date_answer = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("date_answer");
                this.Ondate_answerChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _date_answer;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondate_answerChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondate_answerChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété deleted dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool deleted
        {
            get
            {
                return this._deleted;
            }
            set
            {
                this.OndeletedChanging(value);
                this.ReportPropertyChanging("deleted");
                this._deleted = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("deleted");
                this.OndeletedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _deleted;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndeletedChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndeletedChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Owner dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuestionYourFriendsModel", "FK_Question_Owner", "User")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User Owner
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Owner", "User").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Owner", "User").Value = value;
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Owner dans le schéma.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> OwnerReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Owner", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Owner", "User", value);
                }
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Receiver dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuestionYourFriendsModel", "FK_Question_Receiver", "User")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User Receiver
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Receiver", "User").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Receiver", "User").Value = value;
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Receiver dans le schéma.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> ReceiverReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Receiver", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Receiver", "User", value);
                }
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Transacs dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuestionYourFriendsModel", "FK_Transac_Question", "Transac")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Transac> Transacs
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Transac>("QuestionYourFriendsModel.FK_Transac_Question", "Transac");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Transac>("QuestionYourFriendsModel.FK_Transac_Question", "Transac", value);
                }
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour QuestionYourFriendsModel.Transac dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QuestionYourFriendsModel", Name="Transac")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Transac : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet Transac.
        /// </summary>
        /// <param name="id">Valeur initiale de id.</param>
        /// <param name="amount">Valeur initiale de amount.</param>
        /// <param name="status">Valeur initiale de status.</param>
        /// <param name="type">Valeur initiale de type.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Transac CreateTransac(int id, int amount, int status, int type)
        {
            Transac transac = new Transac();
            transac.id = id;
            transac.amount = amount;
            transac.status = status;
            transac.type = type;
            return transac;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété amount dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int amount
        {
            get
            {
                return this._amount;
            }
            set
            {
                this.OnamountChanging(value);
                this.ReportPropertyChanging("amount");
                this._amount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("amount");
                this.OnamountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _amount;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnamountChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnamountChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété status dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int status
        {
            get
            {
                return this._status;
            }
            set
            {
                this.OnstatusChanging(value);
                this.ReportPropertyChanging("status");
                this._status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("status");
                this.OnstatusChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _status;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnstatusChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnstatusChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété type dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int type
        {
            get
            {
                return this._type;
            }
            set
            {
                this.OntypeChanging(value);
                this.ReportPropertyChanging("type");
                this._type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("type");
                this.OntypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _type;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntypeChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntypeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Question dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuestionYourFriendsModel", "FK_Transac_Question", "Question")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Question Question
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Question>("QuestionYourFriendsModel.FK_Transac_Question", "Question").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Question>("QuestionYourFriendsModel.FK_Transac_Question", "Question").Value = value;
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Question dans le schéma.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Question> QuestionReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Question>("QuestionYourFriendsModel.FK_Transac_Question", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Question>("QuestionYourFriendsModel.FK_Transac_Question", "Question", value);
                }
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour User dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuestionYourFriendsModel", "FK_Transac_User", "User")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("QuestionYourFriendsModel.FK_Transac_User", "User").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("QuestionYourFriendsModel.FK_Transac_User", "User").Value = value;
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour User dans le schéma.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("QuestionYourFriendsModel.FK_Transac_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("QuestionYourFriendsModel.FK_Transac_User", "User", value);
                }
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour QuestionYourFriendsModel.User dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QuestionYourFriendsModel", Name="User")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class User : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet User.
        /// </summary>
        /// <param name="id">Valeur initiale de id.</param>
        /// <param name="fid">Valeur initiale de fid.</param>
        /// <param name="credit_amount">Valeur initiale de credit_amount.</param>
        /// <param name="activated">Valeur initiale de activated.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static User CreateUser(int id, long fid, int credit_amount, bool activated)
        {
            User user = new User();
            user.id = id;
            user.fid = fid;
            user.credit_amount = credit_amount;
            user.activated = activated;
            return user;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété fid dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long fid
        {
            get
            {
                return this._fid;
            }
            set
            {
                this.OnfidChanging(value);
                this.ReportPropertyChanging("fid");
                this._fid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fid");
                this.OnfidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _fid;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfidChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété credit_amount dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int credit_amount
        {
            get
            {
                return this._credit_amount;
            }
            set
            {
                this.Oncredit_amountChanging(value);
                this.ReportPropertyChanging("credit_amount");
                this._credit_amount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("credit_amount");
                this.Oncredit_amountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _credit_amount;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Oncredit_amountChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Oncredit_amountChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété activated dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool activated
        {
            get
            {
                return this._activated;
            }
            set
            {
                this.OnactivatedChanging(value);
                this.ReportPropertyChanging("activated");
                this._activated = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("activated");
                this.OnactivatedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _activated;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnactivatedChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnactivatedChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété login dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string login
        {
            get
            {
                return this._login;
            }
            set
            {
                this.OnloginChanging(value);
                this.ReportPropertyChanging("login");
                this._login = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("login");
                this.OnloginChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _login;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnloginChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnloginChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété passwd dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string passwd
        {
            get
            {
                return this._passwd;
            }
            set
            {
                this.OnpasswdChanging(value);
                this.ReportPropertyChanging("passwd");
                this._passwd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("passwd");
                this.OnpasswdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _passwd;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnpasswdChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnpasswdChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour MyQuestions dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuestionYourFriendsModel", "FK_Question_Owner", "Question")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Question> MyQuestions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Question>("QuestionYourFriendsModel.FK_Question_Owner", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Question>("QuestionYourFriendsModel.FK_Question_Owner", "Question", value);
                }
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour QuestionsToMe dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuestionYourFriendsModel", "FK_Question_Receiver", "Question")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Question> QuestionsToMe
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Question>("QuestionYourFriendsModel.FK_Question_Receiver", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Question>("QuestionYourFriendsModel.FK_Question_Receiver", "Question", value);
                }
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Transacs dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuestionYourFriendsModel", "FK_Transac_User", "Transac")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Transac> Transacs
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Transac>("QuestionYourFriendsModel.FK_Transac_User", "Transac");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Transac>("QuestionYourFriendsModel.FK_Transac_User", "Transac", value);
                }
            }
        }
    }
}
