//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace QuestionYourFriendsDataAccess
{
    public class Question
    {
        #region Primitive Properties

        private int _id_owner;
        private int _id_receiver;
        public virtual int id { get; set; }

        public virtual int id_owner
        {
            get { return _id_owner; }
            set
            {
                if (_id_owner != value)
                {
                    if (Owner != null && Owner.id != value)
                    {
                        Owner = null;
                    }
                    _id_owner = value;
                }
            }
        }

        public virtual int id_receiver
        {
            get { return _id_receiver; }
            set
            {
                if (_id_receiver != value)
                {
                    if (Receiver != null && Receiver.id != value)
                    {
                        Receiver = null;
                    }
                    _id_receiver = value;
                }
            }
        }

        public virtual string text { get; set; }

        public virtual string answer { get; set; }

        public virtual int anom_price { get; set; }

        public virtual int private_price { get; set; }

        public virtual bool undesirable { get; set; }

        public virtual DateTime date_pub { get; set; }

        public virtual DateTime? date_answer { get; set; }

        public virtual bool deleted { get; set; }

        #endregion

        #region Navigation Properties

        private User _owner;

        private User _receiver;

        private ICollection<Transac> _transacs;

        public virtual User Owner
        {
            get { return _owner; }
            set
            {
                if (!ReferenceEquals(_owner, value))
                {
                    User previousValue = _owner;
                    _owner = value;
                    FixupOwner(previousValue);
                }
            }
        }

        public virtual User Receiver
        {
            get { return _receiver; }
            set
            {
                if (!ReferenceEquals(_receiver, value))
                {
                    User previousValue = _receiver;
                    _receiver = value;
                    FixupReceiver(previousValue);
                }
            }
        }

        public virtual ICollection<Transac> Transacs
        {
            get
            {
                if (_transacs == null)
                {
                    var newCollection = new FixupCollection<Transac>();
                    newCollection.CollectionChanged += FixupTransacs;
                    _transacs = newCollection;
                }
                return _transacs;
            }
            set
            {
                if (!ReferenceEquals(_transacs, value))
                {
                    var previousValue = _transacs as FixupCollection<Transac>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTransacs;
                    }
                    _transacs = value;
                    var newValue = value as FixupCollection<Transac>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTransacs;
                    }
                }
            }
        }

        #endregion

        #region Association Fixup

        private void FixupOwner(User previousValue)
        {
            if (previousValue != null && previousValue.MyQuestions.Contains(this))
            {
                previousValue.MyQuestions.Remove(this);
            }

            if (Owner != null)
            {
                if (!Owner.MyQuestions.Contains(this))
                {
                    Owner.MyQuestions.Add(this);
                }
                if (id_owner != Owner.id)
                {
                    id_owner = Owner.id;
                }
            }
        }

        private void FixupReceiver(User previousValue)
        {
            if (previousValue != null && previousValue.QuestionsToMe.Contains(this))
            {
                previousValue.QuestionsToMe.Remove(this);
            }

            if (Receiver != null)
            {
                if (!Receiver.QuestionsToMe.Contains(this))
                {
                    Receiver.QuestionsToMe.Add(this);
                }
                if (id_receiver != Receiver.id)
                {
                    id_receiver = Receiver.id;
                }
            }
        }

        private void FixupTransacs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Transac item in e.NewItems)
                {
                    item.Question = this;
                }
            }

            if (e.OldItems != null)
            {
                foreach (Transac item in e.OldItems)
                {
                    if (ReferenceEquals(item.Question, this))
                    {
                        item.Question = null;
                    }
                }
            }
        }

        #endregion
    }
}