//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.EntityClient;
using System.Data.Objects;

namespace QuestionYourFriendsDataAccess
{
    public class QuestionYourFriendsEntities : ObjectContext
    {
        public const string ConnectionString = "name=QuestionYourFriendsEntities";
        public const string ContainerName = "QuestionYourFriendsEntities";

        #region Constructors

        public QuestionYourFriendsEntities()
            : base(ConnectionString, ContainerName)
        {
            ContextOptions.LazyLoadingEnabled = true;
        }

        public QuestionYourFriendsEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            ContextOptions.LazyLoadingEnabled = true;
        }

        public QuestionYourFriendsEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            ContextOptions.LazyLoadingEnabled = true;
        }

        #endregion

        #region ObjectSet Properties

        private ObjectSet<Question> _questions;

        private ObjectSet<Transac> _transacs;

        private ObjectSet<User> _users;

        public ObjectSet<Question> Questions
        {
            get { return _questions ?? (_questions = CreateObjectSet<Question>("Questions")); }
        }

        public ObjectSet<Transac> Transacs
        {
            get { return _transacs ?? (_transacs = CreateObjectSet<Transac>("Transacs")); }
        }

        public ObjectSet<User> Users
        {
            get { return _users ?? (_users = CreateObjectSet<User>("Users")); }
        }

        #endregion
    }
}