//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionYourFriendsDataAccess
{
    public class Transac
    {
        #region Primitive Properties

        private int _questionId;
        private int _userId;
        public virtual int id { get; set; }

        public virtual int amount { get; set; }

        public virtual int status { get; set; }

        public virtual int userId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (User != null && User.id != value)
                    {
                        User = null;
                    }
                    _userId = value;
                }
            }
        }

        public virtual int type { get; set; }

        public virtual int questionId
        {
            get { return _questionId; }
            set
            {
                if (_questionId != value)
                {
                    if (Question != null && Question.id != value)
                    {
                        Question = null;
                    }
                    _questionId = value;
                }
            }
        }

        #endregion

        #region Navigation Properties

        private Question _question;

        private User _user;

        public virtual Question Question
        {
            get { return _question; }
            set
            {
                if (!ReferenceEquals(_question, value))
                {
                    Question previousValue = _question;
                    _question = value;
                    FixupQuestion(previousValue);
                }
            }
        }

        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    User previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }

        #endregion

        #region Association Fixup

        private void FixupQuestion(Question previousValue)
        {
            if (previousValue != null && previousValue.Transacs.Contains(this))
            {
                previousValue.Transacs.Remove(this);
            }

            if (Question != null)
            {
                if (!Question.Transacs.Contains(this))
                {
                    Question.Transacs.Add(this);
                }
                if (questionId != Question.id)
                {
                    questionId = Question.id;
                }
            }
        }

        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.Transacs.Contains(this))
            {
                previousValue.Transacs.Remove(this);
            }

            if (User != null)
            {
                if (!User.Transacs.Contains(this))
                {
                    User.Transacs.Add(this);
                }
                if (userId != User.id)
                {
                    userId = User.id;
                }
            }
        }

        #endregion
    }
}