//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("QuestionYourFriendsModel", "FK_Question_Owner", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(qyf.DataAccess.User), "Question", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(qyf.DataAccess.Question), true)]
[assembly: EdmRelationshipAttribute("QuestionYourFriendsModel", "FK_Question_Receiver", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(qyf.DataAccess.User), "Question", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(qyf.DataAccess.Question), true)]

#endregion

namespace qyf.DataAccess
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class QuestionYourFriendsEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet QuestionYourFriendsEntities à l'aide de la chaîne de connexion trouvée dans la section 'QuestionYourFriendsEntities' du fichier de configuration d'application.
        /// </summary>
        public QuestionYourFriendsEntities() : base("name=QuestionYourFriendsEntities", "QuestionYourFriendsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet QuestionYourFriendsEntities.
        /// </summary>
        public QuestionYourFriendsEntities(string connectionString) : base(connectionString, "QuestionYourFriendsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet QuestionYourFriendsEntities.
        /// </summary>
        public QuestionYourFriendsEntities(EntityConnection connection) : base(connection, "QuestionYourFriendsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Question> Questions
        {
            get
            {
                if ((_Questions == null))
                {
                    _Questions = base.CreateObjectSet<Question>("Questions");
                }
                return _Questions;
            }
        }
        private ObjectSet<Question> _Questions;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Transac> Transacs
        {
            get
            {
                if ((_Transacs == null))
                {
                    _Transacs = base.CreateObjectSet<Transac>("Transacs");
                }
                return _Transacs;
            }
        }
        private ObjectSet<Transac> _Transacs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Questions. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToQuestions(Question question)
        {
            base.AddObject("Questions", question);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Transacs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToTransacs(Transac transac)
        {
            base.AddObject("Transacs", transac);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Users. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuestionYourFriendsModel", Name="Question")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Question : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Question.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        public static Question CreateQuestion(global::System.Int32 id)
        {
            Question question = new Question();
            question.id = id;
            return question;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_owner
        {
            get
            {
                return _id_owner;
            }
            set
            {
                Onid_ownerChanging(value);
                ReportPropertyChanging("id_owner");
                _id_owner = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_owner");
                Onid_ownerChanged();
            }
        }
        private Nullable<global::System.Int32> _id_owner;
        partial void Onid_ownerChanging(Nullable<global::System.Int32> value);
        partial void Onid_ownerChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_receiver
        {
            get
            {
                return _id_receiver;
            }
            set
            {
                Onid_receiverChanging(value);
                ReportPropertyChanging("id_receiver");
                _id_receiver = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_receiver");
                Onid_receiverChanged();
            }
        }
        private Nullable<global::System.Int32> _id_receiver;
        partial void Onid_receiverChanging(Nullable<global::System.Int32> value);
        partial void Onid_receiverChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String text
        {
            get
            {
                return _text;
            }
            set
            {
                OntextChanging(value);
                ReportPropertyChanging("text");
                _text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("text");
                OntextChanged();
            }
        }
        private global::System.String _text;
        partial void OntextChanging(global::System.String value);
        partial void OntextChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String answer
        {
            get
            {
                return _answer;
            }
            set
            {
                OnanswerChanging(value);
                ReportPropertyChanging("answer");
                _answer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("answer");
                OnanswerChanged();
            }
        }
        private global::System.String _answer;
        partial void OnanswerChanging(global::System.String value);
        partial void OnanswerChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> anom_price
        {
            get
            {
                return _anom_price;
            }
            set
            {
                Onanom_priceChanging(value);
                ReportPropertyChanging("anom_price");
                _anom_price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("anom_price");
                Onanom_priceChanged();
            }
        }
        private Nullable<global::System.Int32> _anom_price;
        partial void Onanom_priceChanging(Nullable<global::System.Int32> value);
        partial void Onanom_priceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> private_price
        {
            get
            {
                return _private_price;
            }
            set
            {
                Onprivate_priceChanging(value);
                ReportPropertyChanging("private_price");
                _private_price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("private_price");
                Onprivate_priceChanged();
            }
        }
        private Nullable<global::System.Int32> _private_price;
        partial void Onprivate_priceChanging(Nullable<global::System.Int32> value);
        partial void Onprivate_priceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> undesirable
        {
            get
            {
                return _undesirable;
            }
            set
            {
                OnundesirableChanging(value);
                ReportPropertyChanging("undesirable");
                _undesirable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("undesirable");
                OnundesirableChanged();
            }
        }
        private Nullable<global::System.Boolean> _undesirable;
        partial void OnundesirableChanging(Nullable<global::System.Boolean> value);
        partial void OnundesirableChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_pub
        {
            get
            {
                return _date_pub;
            }
            set
            {
                Ondate_pubChanging(value);
                ReportPropertyChanging("date_pub");
                _date_pub = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_pub");
                Ondate_pubChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_pub;
        partial void Ondate_pubChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_pubChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_answer
        {
            get
            {
                return _date_answer;
            }
            set
            {
                Ondate_answerChanging(value);
                ReportPropertyChanging("date_answer");
                _date_answer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_answer");
                Ondate_answerChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_answer;
        partial void Ondate_answerChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_answerChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuestionYourFriendsModel", "FK_Question_Owner", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Owner", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Owner", "User").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Owner", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Owner", "User", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuestionYourFriendsModel", "FK_Question_Receiver", "User")]
        public User User1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Receiver", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Receiver", "User").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> User1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Receiver", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("QuestionYourFriendsModel.FK_Question_Receiver", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuestionYourFriendsModel", Name="Transac")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Transac : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Transac.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        public static Transac CreateTransac(global::System.Int32 id)
        {
            Transac transac = new Transac();
            transac.id = id;
            return transac;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> fid
        {
            get
            {
                return _fid;
            }
            set
            {
                OnfidChanging(value);
                ReportPropertyChanging("fid");
                _fid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fid");
                OnfidChanged();
            }
        }
        private Nullable<global::System.Int64> _fid;
        partial void OnfidChanging(Nullable<global::System.Int64> value);
        partial void OnfidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> amount
        {
            get
            {
                return _amount;
            }
            set
            {
                OnamountChanging(value);
                ReportPropertyChanging("amount");
                _amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("amount");
                OnamountChanged();
            }
        }
        private Nullable<global::System.Int32> _amount;
        partial void OnamountChanging(Nullable<global::System.Int32> value);
        partial void OnamountChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuestionYourFriendsModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet User.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        public static User CreateUser(global::System.Int32 id)
        {
            User user = new User();
            user.id = id;
            return user;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> fid
        {
            get
            {
                return _fid;
            }
            set
            {
                OnfidChanging(value);
                ReportPropertyChanging("fid");
                _fid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fid");
                OnfidChanged();
            }
        }
        private Nullable<global::System.Int64> _fid;
        partial void OnfidChanging(Nullable<global::System.Int64> value);
        partial void OnfidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> credit_amount
        {
            get
            {
                return _credit_amount;
            }
            set
            {
                Oncredit_amountChanging(value);
                ReportPropertyChanging("credit_amount");
                _credit_amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("credit_amount");
                Oncredit_amountChanged();
            }
        }
        private Nullable<global::System.Int32> _credit_amount;
        partial void Oncredit_amountChanging(Nullable<global::System.Int32> value);
        partial void Oncredit_amountChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> activated
        {
            get
            {
                return _activated;
            }
            set
            {
                OnactivatedChanging(value);
                ReportPropertyChanging("activated");
                _activated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("activated");
                OnactivatedChanged();
            }
        }
        private Nullable<global::System.Boolean> _activated;
        partial void OnactivatedChanging(Nullable<global::System.Boolean> value);
        partial void OnactivatedChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuestionYourFriendsModel", "FK_Question_Owner", "Question")]
        public EntityCollection<Question> Questions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Question>("QuestionYourFriendsModel.FK_Question_Owner", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Question>("QuestionYourFriendsModel.FK_Question_Owner", "Question", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuestionYourFriendsModel", "FK_Question_Receiver", "Question")]
        public EntityCollection<Question> Questions1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Question>("QuestionYourFriendsModel.FK_Question_Receiver", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Question>("QuestionYourFriendsModel.FK_Question_Receiver", "Question", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
